//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>
using namespace std;

int main()
{
    int sum = 0;
    int count = 0;

    int a = 1;
    int b = 2;
    int hold = 0;
    while(a < 4000000)
    {

        if (!(b%2))
        {
            cout << b << " " ;
            sum+=b;
        }

        hold = a+b;
        a = b;
        b = hold;

    }
    cout << endl;
    cout << sum;
    //4613732



}
